using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using AnimesBackEnd;
//
//    var temporada = Temporada.FromJson(jsonString);

namespace AnimesBackEnd
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Temporada
    {
        [JsonProperty("id")]
        public int Id { get; set; }

        [JsonProperty("descricao")]
        public string Descricao { get; set; }

        [JsonProperty("animes")]
        public Animes Animes { get; set; }

        [JsonProperty("episodios")]
        public Episodio[] Episodios { get; set; }
    }

    public partial class Animes
    {
        [JsonProperty("id")]
        public int Id { get; set; }
    }

    public partial class Temporada
    {
        public static Temporada[] FromJson(string json) => JsonConvert.DeserializeObject<Temporada[]>(json, AnimesBackEnd.Converter.Settings);
    }

    public partial class TemporadaAdd
    {
       
        [JsonProperty("descricao")]
        public string Descricao { get; set; }

    }


}
